'use strict';

const data = [
  {
    id: 1,
    phone: '13810556559',
    email: 'user@user.com',
    username: 'test_user1',
    coin: 20,
    status: 1,
    password: '$2a$10$QlA.DnpNNoehYSsfoCPm.eMkv8Bujwbvl5x3r6afmO12E0PdQD3kO',
    avatar: 'http://so.com',
    scope: 'normal',
    version: 0,
  },
  {
    id: 2,
    phone: '13810556558',
    email: 'user2@user.com',
    username: 'test_user2_phone',
    coin: 20,
    status: 1,
    password: '',
    avatar: 'http://so.com',
    scope: 'normal',
    version: 0,
  },
  {
    id: 3,
    phone: '11189712893',
    email: null,
    wxOpenid: '123847832947529',
    username: 'test_user3_wechat',
    coin: 20,
    status: 1,
    password: '',
    avatar: 'http://so.com',
    scope: 'normal',
    version: 0,
  },
  {
    id: 4,
    phone: null,
    email: null,
    wxOpenid: null,
    username: 'test_user4_visitor',
    coin: 0,
    status: 1,
    password: null,
    avatar: null,
    scope: 'visitor',
    lastSignImei: 'imei:123:123:123',
    version: 0,
  },
  {
    id: 5,
    phone: null,
    email: null,
    wxOpenid: null,
    username: 'test_user4_异常账号',
    coin: 0,
    status: 0,
    password: null,
    avatar: null,
    scope: 'visitor',
    lastSignImei: 'imei:123:123:123',
    version: 0,
  },
  // get username for wechat
  {
    id: 6,
    phone: '11189712896',
    email: null,
    wxOpenid: 'wxopenidUserId6',
    username: 'userId6 FromWx',
    coin: 0,
    status: 1,
    password: null,
    avatar: 'http://url/userid/6',
    scope: 'normal',
    lastSignImei: 'imei:124:124:124',
    version: 0,
  },
  {
    id: 100006,
    phone: '12189712896',
    email: null,
    wxOpenid: null,
    username: '',
    coin: 0,
    status: 0,
    password: null,
    avatar: 'http://url/userid/100006',
    scope: 'normal',
    lastSignImei: 'imei:124:124:124:100006',
    version: 0,
  },
  {
    id: 100007,
    phone: null,
    email: null,
    wxOpenid: null,
    username: '',
    coin: 0,
    status: 0,
    password: null,
    avatar: 'http://url/userid/100007',
    scope: 'normal',
    lastSignImei: 'imei:124:124:124:100007',
    version: 0,
  },
  // bind phone
  {
    id: 7,
    phone: null,
    email: null,
    wxOpenid: null,
    username: '',
    coin: 0,
    status: 0,
    password: null,
    avatar: null,
    scope: 'visitor',
    lastSignImei: 'imei:125:123:12131',
    version: 0,
  },
  {
    id: 8,
    phone: '13845886442',
    email: null,
    wxOpenid: null,
    username: '用户推荐1',
    coin: 0,
    status: 0,
    password: null,
    avatar: null,
    scope: 'normal',
    lastSignImei: 'imei:125:123:tuijian',
    version: 0,
  },
  {
    id: 9,
    phone: '13845886445',
    email: null,
    wxOpenid: null,
    username: '用户推荐2',
    coin: 0,
    status: 0,
    password: null,
    avatar: null,
    scope: 'normal',
    lastSignImei: 'imei:125:123:tuijian2',
    version: 0,
  },
  {
    id: 10,
    phone: '13845886447',
    email: null,
    wxOpenid: null,
    username: '被推荐用户1',
    coin: 101,
    status: 0,
    password: null,
    avatar: null,
    scope: 'normal',
    lastSignImei: 'imei:125:123:txdadf',
    version: 0,
  },
  {
    id: 11,
    phone: '13845886448',
    email: null,
    wxOpenid: null,
    username: '被推荐用户1',
    coin: 101,
    status: 0,
    password: null,
    avatar: null,
    scope: 'normal',
    lastSignImei: 'imei:125:123:txdadf',
    version: 0,
  },
  {
    id: 12,
    phone: '13845886551',
    email: null,
    wxOpenid: null,
    username: 'user_read_task_1',
    coin: 0,
    status: 0,
    password: null,
    avatar: null,
    scope: 'normal',
    lastSignImei: 'imei:125:123:txdadf1',
    version: 0,
  },
  {
    id: 13,
    phone: '13845886552',
    email: null,
    wxOpenid: null,
    username: 'user_read_task_2',
    coin: 0,
    status: 0,
    password: null,
    avatar: null,
    scope: 'normal',
    lastSignImei: 'imei:125:123:txdadf2',
    version: 0,
  },
  {
    id: 14,
    phone: '13845886554',
    email: null,
    wxOpenid: null,
    username: 'user_search_task_log_1',
    coin: 0,
    status: 0,
    password: null,
    avatar: null,
    scope: 'normal',
    lastSignImei: 'imei:125:123:user_search_task_log_1',
    version: 0,
  },
];

module.exports = data;
